### ISSUE TITLE
RDF::Isomorphic is not passed to RDF::Queryable::Enumerator

### ISSUE THREAD

**Issue by jperville** [ruby-rdf/rdf-isomorphic#3]
# The bug

For versions of `rdf > 1.1.3` (works with earlier versions), we expect `RDF::Isomorphic` to be included everywhere `RDF::Enumerable` is included (because `RDF::Isomorphic` patches the `RDF::Enumerable` module to include itself). However, when running the `spira` test suite (with rdf-isomorphic 1.1.0 and rdf = 1.1.16 ) at least one assertion fails because `RDF::Isomorphic` is not present in an object that is `RDF::Enumerable`.
# Demonstration

Run this in a `bundle console` started on a working copy of rdf-isomorphic after installing the bundle.

``` sh
irb(main):001:0> require 'rdf/isomorphic'
=> false
irb(main):002:0> RDF::Queryable::Enumerator
=> RDF::Queryable::Enumerator
irb(main):003:0> RDF::Queryable::Enumerator < RDF::Enumerable
=> true
irb(main):004:0> RDF::Enumerable < RDF::Isomorphic
=> true
irb(main):005:0> RDF::Queryable::Enumerator < RDF::Isomorphic
=> nil # <--- bug
```

We would have expected `RDF::Queryable::Enumerator` to have `RDF::Isomorphic` in its ancestors since it is an `RDF::Enumerable` and `RDF::Enumerable` has `RDF::Isomorphic` in its ancestors.
# The reason

The reason lies in the use of `Kernel.extend` here: https://github.com/ruby-rdf/rdf/blob/develop/lib/rdf/mixin/enumerable.rb#L720 , which extends `RDF::Enumerator` with `RDF::Enumerable` before this gem got a chance to include itself in `RDF::Enumerable`.
# Bug or gotcha in Ruby?

I don't know if it is a bug or a gotcha in Ruby, but I can reproduce this behavior: monkeypatching a module won't work with objects that extend that module before the monkeypatching (this is counter intuitive)

``` sh
irb(main):001:0> module M ; end
=> nil
irb(main):002:0> module N ; end
=> nil
irb(main):003:0> class K ; end
=> nil
irb(main):004:0> k = K.new.extend(M)
=> #<K:0x00000000acf8c8>
irb(main):005:0> k.class.ancestors
=> [K, Object, Kernel, BasicObject]
irb(main):006:0> k.singleton_class.ancestors
=> [#<Class:#<K:0x00000000acf8c8>>, M, K, Object, Kernel, BasicObject]
irb(main):007:0> module M ; include N ; end
=> M
irb(main):008:0> k.singleton_class.ancestors
=> [#<Class:#<K:0x00000000acf8c8>>, M, K, Object, Kernel, BasicObject] # <--- we would have expected N to be present in k's ancestors since k includes M and M has been redefined to include N
irb(main):009:0> k2 = K.new.extend(M)
=> #<K:0x00000000aadf98>
irb(main):010:0> k2.singleton_class.ancestors
=> [#<Class:#<K:0x00000000aadf98>>, M, N, K, Object, Kernel, BasicObject] # <--- works as expected because the extend happened after the monkey patching has been done
irb(main):011:0> 
```

**Comment by gkellogg** [comment]
Thanks for the great analysis! This should be fixed on the 'develop' branch of RDF.rb. I'll see about adding a test for this.

**Comment by jperville** [comment]
Thank you for the fast fix @gkellogg , I learned something about extend behavior while investigating this.

**Comment by gkellogg** [comment]
Me too!
